### ISSUE TITLE
[AxQuestboard]

### ISSUE THREAD

**Issue by wattywatty14** [Artillex-Studios/Issues#129]
### Description of the bug

I don't know how it happened, but the questboard isn't properly resetting. I tried doing /questboard resetboard, but it came up with [this error. ](https://pastebin.com/Sx8W2cTB) I also tried reloading the plugin, and that didn't work. I tried restarting the plugin, and it didn't work.  No errors on startup. Is this intentional or a bug?

![Image](https://github.com/user-attachments/assets/af5cf428-fbaf-4006-8b23-7bf00676ae15)

### Expected behaviour

I expected it to reset properly.

### Steps to reproduce

I don't know. I tried recreating the error, but it's not creating a log. 

### Which plugin is this issue with?

axquestboard

### Versions

![Image](https://github.com/user-attachments/assets/0218d1ad-c3da-4291-91fb-46137a828cf2)

![Image](https://github.com/user-attachments/assets/bdb1130c-dcd1-4e41-a917-091be60526ae)

**Comment by wattywatty14** [comment]
Got another error when trying to reset the questboard - view it[ here. ](https://pastebin.com/k0nBMJAA)

**Comment by MODNMETL** [comment]
Can confirm we are getting this issue, too since updating the plugin to 1.12.0

**Comment by BenceX100** [comment]
The NoClassDefFoundError issue should be fixed in 1.12.1.

The user thing should never happen, that means that the user got a score without ever joining the server. Not sure what could cause it.

**Comment by MODNMETL** [comment]
> The NoClassDefFoundError issue should be fixed in 1.12.1.
> 
> The user thing should never happen, that means that the user got a score without ever joining the server. Not sure what could cause it.

Thanks, yeah the 1.12.1 version has resolved the stuck refresh issue, but we're still getting that "java.lang.RuntimeException: User not found!" error coming up in console. Is there a way I can see which user account is triggering that in AXQB? I don't see a debug mode in the config, is there one?

**Comment by BenceX100** [comment]
This should be fixed. If not, feel free to reopen.
